 /*
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package GUI;

import java.awt.Color;

/**
 *
 * @author zeus
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        this.JTxtEmail.setForeground(Color.WHITE);
        this.JTxtPassword.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JBtnLeerCorreo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        JTxtBusqueda = new javax.swing.JTextField();
        JBtnConsultar = new javax.swing.JButton();
        JTxtEmail = new javax.swing.JTextField();
        JTxtPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTBtnMostarMail = new javax.swing.JToggleButton();
        JlblSubjet = new javax.swing.JLabel();
        JRBDni = new javax.swing.JRadioButton();
        JRbNombre = new javax.swing.JRadioButton();
        JRbProcedimiento = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBtnLeerCorreo.setText("LeerCorreo");
        JBtnLeerCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLeerCorreoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jEditorPane1);

        JTxtBusqueda.setText("SELECT  *  FROM CLIENTES");

        JBtnConsultar.setText("Consultar");
        JBtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnConsultarActionPerformed(evt);
            }
        });

        JTxtEmail.setText("micorreo@gmail.com");

        JTxtPassword.setText("micontraseña");
        JTxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtPasswordActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario:");

        jLabel2.setText("Password");

        JTBtnMostarMail.setText("Mostrar conf email");
        JTBtnMostarMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTBtnMostarMailActionPerformed(evt);
            }
        });

        JlblSubjet.setText("Subjet:");

        buttonGroup1.add(JRBDni);
        JRBDni.setText("DNI");

        buttonGroup1.add(JRbNombre);
        JRbNombre.setText("NOMBRE");

        buttonGroup1.add(JRbProcedimiento);
        JRbProcedimiento.setText("PROCEDIMIENTO");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("SQL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JRBDni)
                        .addGap(18, 18, 18)
                        .addComponent(JRbNombre)
                        .addGap(26, 26, 26)
                        .addComponent(JRbProcedimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(JTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(JTBtnMostarMail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JlblSubjet, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(JBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBtnLeerCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(JTBtnMostarMail))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnConsultar)
                    .addComponent(JRBDni)
                    .addComponent(JRbNombre)
                    .addComponent(JRbProcedimiento)
                    .addComponent(JBtnLeerCorreo)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JlblSubjet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnLeerCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLeerCorreoActionPerformed
        // TODO add your handling code here:
        modelo.Remitente re = modelo.MAIL.RecibirMail(this.JTxtEmail.getText(), this.JTxtPassword.getText());
        this.jEditorPane1.setContentType("text/html");
        this.jEditorPane1.setText(re.getBody());
        this.JlblSubjet.setText(re.getEmail() + " " + re.getTexto());


    }//GEN-LAST:event_JBtnLeerCorreoActionPerformed

    private void JBtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnConsultarActionPerformed
        // TODO add your handling code here:
        String texto = this.JTxtBusqueda.getText().replace("'", "").replaceAll(",", "");

        if (this.JRBDni.isSelected()) {
            modelo.MAIL.EnviarMail("DNI=[" + texto + "]", "", this.JTxtEmail.getText(), this.JTxtPassword.getText());
        }

        if (this.JRbNombre.isSelected()) {
            modelo.MAIL.EnviarMail("NOMBRE=[" + texto + "]", "", this.JTxtEmail.getText(), this.JTxtPassword.getText());
        }

        if (this.JRbProcedimiento.isSelected()) {
            modelo.MAIL.EnviarMail("PROCEDIMIENTO=[" + texto + "]", "", this.JTxtEmail.getText(), this.JTxtPassword.getText());
        }

        if (this.jRadioButton1.isSelected()) {
            modelo.MAIL.EnviarMail("SQL=[]", this.JTxtBusqueda.getText(), this.JTxtEmail.getText(), this.JTxtPassword.getText());
        }

    }//GEN-LAST:event_JBtnConsultarActionPerformed

    private void JTxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtPasswordActionPerformed

    private void JTBtnMostarMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTBtnMostarMailActionPerformed
        // TODO add your handling code here:
        if (this.JTBtnMostarMail.isSelected()) {

            this.JTBtnMostarMail.setText("Ocultar Conf Email");
            this.JTxtEmail.setForeground(Color.BLACK);
            this.JTxtPassword.setForeground(Color.BLACK);

        } else {
            this.JTBtnMostarMail.setText("Mostrar Conf Email");

            this.JTxtEmail.setForeground(Color.WHITE);
            this.JTxtPassword.setForeground(Color.WHITE);
        }


    }//GEN-LAST:event_JTBtnMostarMailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnConsultar;
    private javax.swing.JButton JBtnLeerCorreo;
    private javax.swing.JRadioButton JRBDni;
    private javax.swing.JRadioButton JRbNombre;
    private javax.swing.JRadioButton JRbProcedimiento;
    private javax.swing.JToggleButton JTBtnMostarMail;
    private javax.swing.JTextField JTxtBusqueda;
    private javax.swing.JTextField JTxtEmail;
    private javax.swing.JTextField JTxtPassword;
    private javax.swing.JLabel JlblSubjet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
